using EulerLib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace P02
{
    /// <summary>
    /// A Solution to Euler problem 2 - https://projecteuler.net/problem=2
    /// 
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, 
    /// the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
    /// even-valued terms
    /// 
    /// Answer: 4613732
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            BigInteger max = 4000000 - 1;
            BigInteger sum = EMath.SumOfEvenFibonacci(max);

            Console.WriteLine("The sum of even valued Fibonacci numbers <= {0} is {1}", max, sum);
        }
    }
}
