using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, 
    /// the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
    /// even-valued terms
    /// 
    /// Answer: 4613732
    /// </summary>
    public static class p2
    {
        public static BigInteger sum()
        {
            BigInteger a = 0;
            BigInteger b = 1;
            BigInteger tmp = a + b;
            BigInteger sum = 0;


            while (a < 4000000)
            {
                if (a % 2 == 0)
                    sum += a;

                tmp = a + b;
                a = b;
                b = tmp; 
            }

            return sum;
        }
    }
}
